In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 上市公司各產業EPS統計資訊

In [3]:
df=pd.read_csv("http://mopsfin.twse.com.tw/opendata/t187ap14_L.csv")

In [4]:
df

,出表日期,年度,季別,公司代號,公司名稱,產業別,基本每股盈餘(元),普通股每股面額,營業收入,營業利益,營業外收入及支出,稅後淨利
0,109/03/17,108,4,1236,宏亞食品股份有限公司,食品工業,0.15,新台幣 10.0000元,1864663.0,1000.00,16698.00,15779.0
1,109/03/17,108,4,1307,三芳化學工業股份有限公司,塑膠工業,1.08,新台幣 10.0000元,10271411.0,651090.00,-10444.00,430420.0
2,109/03/17,108,4,1310,台灣苯乙烯工業股份有限公司,塑膠工業,1.67,新台幣 10.0000元,12219389.0,1070680.00,-35920.00,881756.0
3,109/03/17,108,4,1313,聯成化學科技股份有限公司,塑膠工業,-0.11,新台幣 10.0000元,62714942.0,-354188.00,175555.00,-140376.0
4,109/03/17,108,4,1323,永裕塑膠工業股份有限公司,塑膠工業,3.18,新台幣 10.0000元,3639735.0,451014.00,8654.00,353283.0
...,...,...,...,...,...,...,...,...,...,...,...,...
201,109/03/17,108,4,9919,康那香企業股份有限公司,其他,0.06,新台幣 10.0000元,4056986.0,25926.00,-9239.00,8836.0
202,109/03/17,108,4,9924,台灣福興工業股份有限公司,其他,4.38,新台幣 10.0000元,8681906.0,1139882.00,14341.00,843191.0
203,109/03/17,108,4,9933,中鼎工程股份有限公司,其他,1.54,新台幣 10.0000元,58211022.0,2168150.00,62165.00,1674325.0
204,109/03/17,108,4,9934,成霖企業股份有限公司,其他,0.94,新台幣 10.0000元,17023426.0,391056.00,92475.00,336055.0
205,109/03/17,108,4,9940,信義房屋股份有限公司,其他,1.71,新台幣 10.0000元,12438032.0,1971558.00,85128.00,1276205.0

In [9]:
df1=df[["公司名稱","基本每股盈餘(元)","營業利益","稅後淨利"]]  #留下想看的資訊

In [10]:
df1

              公司名稱  基本每股盈餘(元)        營業利益       稅後淨利
0       宏亞食品股份有限公司       0.15     1000.00    15779.0
1     三芳化學工業股份有限公司       1.08   651090.00   430420.0
2    台灣苯乙烯工業股份有限公司       1.67  1070680.00   881756.0
3     聯成化學科技股份有限公司      -0.11  -354188.00  -140376.0
4     永裕塑膠工業股份有限公司       3.18   451014.00   353283.0
..             ...        ...         ...        ...
201    康那香企業股份有限公司       0.06    25926.00     8836.0
202   台灣福興工業股份有限公司       4.38  1139882.00   843191.0
203     中鼎工程股份有限公司       1.54  2168150.00  1674325.0
204     成霖企業股份有限公司       0.94   391056.00   336055.0
205     信義房屋股份有限公司       1.71  1971558.00  1276205.0

[206 rows x 4 columns]

In [11]:
 df1.sort_values(by="基本每股盈餘(元)",ascending=False).head()    #看「基本每股盈餘(元)」排名前五的公司

           公司名稱  基本每股盈餘(元)         營業利益        稅後淨利
93   大立光電股份有限公司     210.70  36499337.00  28263082.0
171  旭隼科技股份有限公司      25.87   2557103.00   2131032.0
119  牧德科技股份有限公司      20.01   1070497.00    866869.0
132    麗豐股份有限公司      18.02   1789074.00   1432163.0
31   川湖科技股份有限公司      16.35   2015151.00   1558250.0

In [12]:
df1.sort_values(by="營業利益",ascending=False).head()         #看「營業利益」排名前五的公司

            公司名稱  基本每股盈餘(元)        營業利益       稅後淨利
22    勝一化工股份有限公司       5.90   989218.00   884866.0
163  盛群半導體股份有限公司       4.05   986738.00   922313.0
47    南亞科技股份有限公司       3.23  9516820.00  9824599.0
153    禾聯碩股份有限公司      10.73   946242.00   774334.0
36    光寶科技股份有限公司       4.03  9345222.00  9405517.0

In [13]:
df1.sort_values(by="稅後淨利",ascending=False).head()       

#看「稅後淨利」排名前五的公司，可以發現大立光電股份有限公司	在這三次的排名中共上榜兩次，推測營運狀況良好

               公司名稱  基本每股盈餘(元)          營業利益         稅後淨利
41   台灣積體電路製造股份有限公司      13.32  372701090.00  345343809.0
177      台塑石化股份有限公司       3.86   36785656.00   36748173.0
5      台灣化學纖維股份有限公司       4.89   16489956.00   34448357.0
49       中華電信股份有限公司       4.23   40645854.00   33763943.0
93       大立光電股份有限公司     210.70   36499337.00   28263082.0