In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 全臺灣大專校院校別學生數

In [2]:
df=pd.read_csv("http://stats.moe.gov.tw/files/detail/108/108_student.csv")

In [3]:
df

,大專校院校別學生數,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,108 學年度 SY201902020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,學校代碼,學校名稱,日間∕進修別,等級別,總計,男生計,女生計,一年級男生,一年級女生,二年級男生,...,五年級男生,五年級女生,六年級男生,六年級女生,七年級男生,七年級女生,延修生男生,延修生女生,縣市名稱,體系別
2,0001,國立政治大學,D 日,D 博士,995,561,434,90,85,87,...,70,48,61,55,80,42,0,0,30 臺北市,1 一般
3,0001,國立政治大學,D 日,M 碩士,4023,1861,2162,644,745,593,...,0,0,0,0,0,0,0,0,30 臺北市,1 一般
4,0001,國立政治大學,D 日,B 學士,9585,3912,5673,896,1289,906,...,0,0,0,0,0,0,345,423,30 臺北市,1 一般
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,1293,崇仁醫護管理專科學校,D 日,5 五專,3330,410,2920,81,584,87,...,69,564,0,0,0,0,11,44,10 嘉義縣,2 技職
792,3002,臺北市立大學,D 日,D 博士,234,101,133,14,19,14,...,11,15,10,17,19,30,0,0,30 臺北市,1 一般
793,3002,臺北市立大學,D 日,M 碩士,1215,420,795,156,242,105,...,15,37,12,27,0,0,0,0,30 臺北市,1 一般
794,3002,臺北市立大學,D 日,B 學士,5270,2335,2935,569,738,527,...,0,0,0,0,0,0,166,140,30 臺北市,1 一般
795,3002,臺北市立大學,N 職,M 碩士,1090,298,792,107,274,87,...,14,44,15,25,0,0,0,0,30 臺北市,1 一般

In [4]:
df1=df.sort_values(by=["Unnamed: 5"],ascending=False)    #找男生最多的學校

In [5]:
df1          #男生最多的學校是中國文化大學

,大專校院校別學生數,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
1,學校代碼,學校名稱,日間∕進修別,等級別,總計,男生計,女生計,一年級男生,一年級女生,二年級男生,...,五年級男生,五年級女生,六年級男生,六年級女生,七年級男生,七年級女生,延修生男生,延修生女生,縣市名稱,體系別
275,1006,中國文化大學,D 日,B 學士,20411,9930,10481,2368,2426,2178,...,33,27,0,0,0,0,1037,872,30 臺北市,1 一般
594,1063,育達科技大學,D 日,B 四技,1980,992,988,203,152,261,...,0,0,0,0,0,0,102,64,05 苗栗縣,2 技職
464,1039,玄奘大學,D 日,B 學士,2327,991,1336,208,295,198,...,0,0,0,0,0,0,104,64,18 新竹市,1 一般
604,1064,美和科技大學,N 修,C 二技,667,99,568,0,0,0,...,0,0,0,0,0,0,11,15,13 屏東縣,2 技職
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,1056,東南科技大學,N 修,C 二技,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,01 新北市,2 技職
502,1046,中國科技大學,N 修,X 4+X,5,0,5,0,0,0,...,0,0,0,0,0,0,0,1,30 臺北市,2 技職
260,1003,東吳大學,D 日,X 4+X,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,30 臺北市,1 一般
344,1019,高雄醫學大學,N 修,C 二技,25,0,25,0,0,0,...,0,12,0,0,0,0,0,1,50 高雄市,2 技職
0,108 學年度 SY201902020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN